name: siq-rfid-poc # you probably want to 'snapcraft register <name>'
version: '0.0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: "A bundle of apps: read impinj rfid, filter, send to azure" # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  rfidpoc:
    command: wrapper.sh
    plugs: [home, network, network-bind]

parts:
  # Github repository for IOTA reference implementation: https://github.com/iotaledger/iri.git
  rfidpoc:
    source: https://github.com/rittidate/siq-rfid-poc.git
    plugin: maven
    snap: [-usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/cacerts]
  # This script contains all the commands needed (sets env variables, launches the jar file...) to
  # execute the application
  exec:
    plugin: dump
    source: .
